//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchwimmbadLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buchung()
        {
            this.belegt = new HashSet<Schwimmbahn>();
        }
    
        public int Id { get; set; }
        public string Wochentag { get; set; }
        public System.TimeSpan Beginn { get; set; }
        public System.TimeSpan Ende { get; set; }
        public System.DateTime Starttermin { get; set; }
        public System.DateTime Endtermin { get; set; }
        public Nullable<int> GastId { get; set; }
        public short Schwimmbahnanzahl { get; set; }
    
        public virtual Gast GehörtZu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schwimmbahn> belegt { get; set; }
    }
}
