//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchwimmbadLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gast()
        {
            this.tätigt = new HashSet<Buchung>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Verein { get; set; }
        public bool Mitarbeiter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> tätigt { get; set; }
    }
}
