//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchwimmbadLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schwimmbahn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schwimmbahn()
        {
            this.WirdGebucht = new HashSet<Buchung>();
        }
    
        public int Id { get; set; }
        public short Schwimmbahnnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> WirdGebucht { get; set; }
    }
}
